config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    resources :slips
  end
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  get '/dashboard/admin' => 'admins/slips#dashboard'
  root to: 'admins/slips#dashboard'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/admins/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> 全塾協議会団体向け財務システム(仮) </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <div class="container mx-auto px-auto">
    <% if admin_signed_in? %>
    <div class="bg-blue-100 border border-blue-500 text-blue-700 px-4 py-3 rounded" role="alert">
      <p class="font-bold">LogOnUser</p>
      <p class="text-sm"><%= "#{current_admin.email}" %><%= button_to ':SignOut', destroy_admin_session_path,method: :delete %></p>
    </div>
    <% else %>
      <%= link_to 'SingUp', new_admin_registration_path %>
      <%= link_to 'SignIn', new_admin_session_path %> 
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
  </body>
</html>