config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    resources :slips
  end
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  get '/dashboard/admin' => 'admins/slips#dashboard'
  root to: 'admins/slips#dashboard'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/slip.rb
class Slip < ApplicationRecord
    belongs_to :sspn, optional: true
    belongs_to :user, optional: true
end

app/controllers/admins/slips_controller.rb
class Admins::SlipsController < Admins::ApplicationController
  before_action :set_admins_slip, only: %i[ show edit update destroy ]

  # GET /admins/slips or /admins/slips.json
  def index
    @admins_slips = Slip.all
  end

  #GET /dashboard
  def dashboard
    @admins_slips = Slip.last(4)
    @admins_sspns = Sspn.where.not(id: 99)
    hash = Hash.new()
    hash2 = Hash.new()
    for s in @admins_sspns do
      sum = s.amount
      for i in s.slips do
        sum -= i.amount
      end
      hash[s.number] = sum
    end
    @remain_hash = hash
    for j in User.all() do
      sum2 = 0
      for k in j.slips do
        if k.reimbursement then
          sum2 += k.amount
        end
      end
      hash2[j.email] = sum2
    end
    @user_hash = hash2
  end

  # GET /admins/slips/1 or /admins/slips/1.json
  def show
    @admins_slip = Slip.find(params[:id])
  end

  # GET /admins/slips/new
  def new
    @admins_slip = Slip.new
  end

  # GET /admins/slips/1/edit
  def edit
  end

  # POST /admins/slips or /admins/slips.json
  def create
    @admins_slip = Slip.new(admins_slip_params)

    respond_to do |format|
      if @admins_slip.save
        format.html { redirect_to [:admins, @admins_slip], notice: "Slip was successfully created." }
        format.json { render :show, status: :created, location: @admins_slip }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admins_slip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/slips/1 or /admins/slips/1.json
  def update
    respond_to do |format|
      if @admins_slip.update(admins_slip_params)
        format.html { redirect_to [:admins, @admins_slip], notice: "Slip was successfully updated." }
        format.json { render :show, status: :ok, location: @admins_slip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admins_slip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/slips/1 or /admins/slips/1.json
  def destroy
    @admins_slip.destroy

    respond_to do |format|
      format.html { redirect_to [:admins, @admins_slip], notice: "Slip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admins_slip
      @admins_slip = Slip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admins_slip_params
      params.fetch(:slip, {}).permit(:number, :payee, :amount, :supplement, :sspn_id, :account, :year, :reimbursement, :issue_date, :user_id)
    end
end

app/helpers/admins/slips_helper.rb
module Admins::SlipsHelper
end

app/views/admins/slips/_form.html.erb
<%= form_with(model: [:admins, @admins_slip]) do |form| %>
  <% if admins_slip.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admins_slip.errors.count, "error") %> prohibited this admins_slip form being saved:</h2>

      <ul>
        <% admins_slip.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-4">
    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="slip_number">伝票番号</label>
    <%= form.number_field :number %>  
  </div>
  <div class="mb-4">
    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="slip_payee">支出先</label>
    <%= form.text_field :payee %>  
  </div>
  <div class="mb-4">
    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="slip_amount">金額</label>
    <%= form.number_field :amount %>  
  </div>
  <div class="mb-4">
    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="slip_issue_date">領収書発行日</label>
    <%= form.date_field :issue_date %>  
  </div>
  <div class="mb-4">
    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="slip_supplement">補足</label>
    <%= form.text_field :supplement %>
  </div>
  <div class="mb-4">
    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="slip_sspn_id">特別支出許可番号</label>
    <%= form.collection_select :sspn_id,Sspn.all, :id, :number %>
  </div>
  <div class="mb-4">
    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="slip_account">会計単位</label>
    <%= form.text_field :account %>
  </div>
  <div class="mb-4">
    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="slip_year">会計年度</label>
    <%= form.number_field :year %>
  </div>
    <div class="mb-4">
    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="slip_user_id">出金ユーザー</label>
    <%= form.collection_select :user_id,User.all, :id, :email %>
  </div>
  <div class="mb-4">
    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="slip_reimbursement">出金元</label>
    <%= form.select :reimbursement,[['団体',0],['個人',1]] %>
  </div> 
  <div class="actions">
    <button class="flex-shrink-0 bg-teal-500 hover:bg-teal-700 border-teal-500 hover:border-teal-700 text-sm border-4 text-white py-1 px-2 rounded"><input type="submit" name="commit" value="確定" data-disable-with="Create Slip"></button>
  </div>
<% end %>

app/views/admins/slips/_slip.html.erb
<div id="<%= dom_id slip %>">
</div>

app/views/admins/slips/dashboard.html.erb
<p style="color: green"><%= notice %></p>
<div class="mt-8 mb-12">
  <h1>ダッシュボード</h1>
</div>
<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"><%= link_to "出金伝票", new_admins_slip_path %></button>

<div class="grid grid-cols-2 gap-4">
  <div class="col-span-1">
    <h2>支出一覧</h2>
    <table class="table-auto">
      <thead>
        <th class="px-4 py-2">伝票番号</th>
        <th class="px-4 py-2">金額</th>
        <th class="px-4 py-2">支払先</th>
        <th class="px-4 py-2">領収書発行日</th>
        <th class="px-4 py-2">リンク</th>
      </thead>
      <tbody>
      <% @admins_slips.each do |admins_slip| %>
        <%= render admins_slip %>
        <tr>
          <th class="border px-4 py-2"><%= admins_slip.number %></th>
          <th class="border px-4 py-2"><%= admins_slip.amount %></th>
          <th class="border px-4 py-2"><%= admins_slip.payee %></th>
          <th class="border px-4 py-2"><%= admins_slip.issue_date&.strftime("%Y-%m-%d") %></th>
          <th class="border px-4 py-2"><%= link_to "Show this slip", [:admins, admins_slip] %></th>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-span-2">
    <h2>特別支出残高</h2>
      <table class="table-auto">
        <thead>
          <th class="px-4 py-2">番号</th>
          <th class="px-4 py-2">残高</th>
        </thead>
        <tbody>
          <% @remain_hash.each do |key,value| %>
            <tr>
              <th class="border px-4 py-2"><%= key %></th>
              <th class="border px-4 py-2"><%= value %></th>
            </tr>
          <% end %>
        </tbody>
      </table>
    <h2>立替清算残金</h2>
      <table class="table-auto">
        <thead>
          <th class="px-4 py-2">メールアドレス</th>
          <th class="px-4 py-2">残金</th>
        </thead>
        <tbody>
          <% @user_hash.each do |key,value| %>
            <tr>
              <th class="border px-4 py-2"><%= key %></th>
              <th class="border px-4 py-2"><%= value %></th>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>

app/views/admins/slips/edit.html.erb
<h1>出金伝票修正</h1>

<%= render "form", admins_slip: @admins_slip %>

<br>

<div>
  <%= link_to "Show this slip", [:admins, @admins_slip] %> |
  <%= link_to "Back to slips", admins_slips_path %>
</div>

app/views/admins/slips/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>出金伝票一覧</h1>

<div id="admins_slips">
  <table class="table-auto">
      <thead>
        <th class="px-4 py-2">伝票番号</th>
        <th class="px-4 py-2">金額</th>
        <th class="px-4 py-2">支払先</th>
        <th class="px-4 py-2">領収書発行日</th>
        <th class="px-4 py-2">リンク</th>
      </thead>
      <tbody>
      <% @admins_slips.each do |admins_slip| %>
        <%= render admins_slip %>
        <tr>
          <th class="border px-4 py-2"><%= admins_slip.number %></th>
          <th class="border px-4 py-2"><%= admins_slip.amount %></th>
          <th class="border px-4 py-2"><%= admins_slip.payee %></th>
          <th class="border px-4 py-2"><%= admins_slip.issue_date&.strftime("%Y-%m-%d") %></th>
          <th class="border px-4 py-2"><%= link_to "Show this slip", [:admins, admins_slip] %></th>
        </tr>
      <% end %>
      </tbody>
  </section>
</div>

<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"><%= link_to "出金伝票登録", new_admins_slip_path %></button>

app/views/admins/slips/new.html.erb
<h1>出金伝票登録</h1>

<%= render "form", admins_slip: @admins_slip %>

<br>

<div>
  <%= link_to "Back to slips", admins_slips_path %>
</div>

app/views/admins/slips/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admins_slip %>
<table class="table-auto mt-4 w-full">
<tbody>
  <tr class="border-b">
    <td class="px-4 py-2">伝票番号</td>
    <td class="px-4 py-2"><%= @admins_slip.number %></td>
  </tr>
  <tr class="border-b">
    <td class="px-4 py-2">支払先</td>
    <td class="px-4 py-2"><%= @admins_slip.payee %></td>
  </tr>
  <tr class="border-b">
    <td class="px-4 py-2">金額</td>
    <td class="px-4 py-2"><%= @admins_slip.amount %></td>
  </tr>
  <tr class="border-b">
    <td class="px-4 py-2">領収書発行日</td>
    <td class="px-4 py-2"><%= @admins_slip.issue_date&.strftime("%Y-%m-%d") %></td>
  </tr>
  <tr class="border-b">
    <td class="px-4 py-2">補足</td>
    <td class="px-4 py-2"><%= @admins_slip.supplement %></td>
  </tr>
  <tr class="border-b">
    <td class="px-4 py-2">特別支出許可番号</td>
    <td class="px-4 py-2"><%= @admins_slip.sspn&.number %></td>
  </tr>
  <tr class="border-b">
    <td class="px-4 py-2">会計</td>
    <td class="px-4 py-2"><%= @admins_slip.account %></td>
  </tr>
  <tr class="border-b">
    <td class="px-4 py-2">年度</td>
    <td class="px-4 py-2"><%= @admins_slip.year %></td>
  </tr>
  <tr class="border-b">
    <td class="px-4 py-2">支払元</td>
    <td class="px-4 py-2"><%= @admins_slip.reimbursement %></td>
  </tr>
</tbody>
</table>

<div>
  <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"><%= link_to "修正", edit_admins_slip_path(@admins_slip) %></button> |
  <button class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded"><%= link_to "出金伝票一覧", admins_slips_path %></button>

  <%= button_to "削除", [:admins, @admins_slip], method: :delete,class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
</div>